# Generated by Django 3.0.7 on 2020-06-12 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeSearchVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.TextField(verbose_name='поисковой запрос')),
                ('title', models.TextField(verbose_name='название')),
                ('video_id', models.TextField(verbose_name='айди')),
                ('duration', models.TextField(verbose_name='время')),
                ('thumbnail', models.TextField(verbose_name='картинка')),
            ],
        ),
        migrations.CreateModel(
            name='LikeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_like', models.TextField(verbose_name='нравится')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.YouTubeSearchVideo')),
            ],
        ),
    ]
