# Generated by Django 3.0.7 on 2020-06-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='simpleLikeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.TextField(verbose_name='поисковой запрос')),
                ('title', models.TextField(verbose_name='название')),
                ('video_id', models.TextField(verbose_name='айди')),
                ('duration', models.TextField(verbose_name='время')),
                ('thumbnail', models.TextField(verbose_name='картинка')),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeSearchVideoCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.TextField(verbose_name='поисковой запрос')),
                ('title', models.TextField(verbose_name='название')),
                ('video_id', models.TextField(verbose_name='айди')),
                ('duration', models.TextField(verbose_name='время')),
                ('thumbnail', models.TextField(verbose_name='картинка')),
            ],
        ),
        migrations.DeleteModel(
            name='LikeVideo',
        ),
        migrations.DeleteModel(
            name='YouTubeSearchVideo',
        ),
    ]
