# Generated by Django 3.0.7 on 2020-06-12 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20200613_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simplelikevideo',
            name='search',
        ),
    ]
